# Generated by Django 5.0.7 on 2024-08-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='humidity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
